package fk.retail.ip.requirement.internal.enums;

/**
 * Created by yogeshwari.k on 23/03/17.
 */
public enum FdpRequirementEventType {

    SUPPLIER_ASSIGNED,
    APP_ASSIGNED,
    PROJECTION_CREATED,
    IPC_QUANTITY_OVERRIDE,
    CDO_QUANTITY_OVERRIDE,
    CDO_APP_OVERRIDE,
    CDO_SLA_OVERRIDE,
    CDO_SUPPLIER_OVERRIDE,
    APPROVE,
    CANCEL,
    ORDER_POLICY_QUANTITY,
    CONTROL_POLICY_QUANTITY_OVERRIDE,
    BIZFIN_QUANTITY_RECOMMENDATION,
    BIZFIN_COMMENT_RECOMMENDATION,
    PUSHED_TO_PROC,
    PUSH_TO_PROC_FAILED,
    PROC_CALLBACK_RECEIVED;
    }
